// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriTrack.Infrastructure.Persistence;

#nullable disable

namespace NutriTrack.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutriTrack.Domain.Achievements.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IconName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("NutriTrack.Domain.Achievements.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("LocalDateEarned")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("NutriTrack.Domain.ActivityLevelHistory.ActivityLevelHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ActivityLevel")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "EffectiveFrom");

                    b.ToTable("ActivityLevelHistoryEntries");
                });

            modelBuilder.Entity("NutriTrack.Domain.Authorization.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("NutriTrack.Domain.Authorization.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("NutriTrack.Domain.Authorization.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("NutriTrack.Domain.Countries.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("NutriTrack.Domain.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DefaultCaloriesPerMinute")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsApproved");

                    b.HasIndex("Name");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("NutriTrack.Domain.Groceries.Grocery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<short>("CaloriesPer100")
                        .HasColumnType("smallint");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("GramsPerPiece")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("UnitOfMeasure")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("Groceries");
                });

            modelBuilder.Entity("NutriTrack.Domain.Meals.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("OccurredAtLocal")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCalories")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCarbohydrates")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("TotalFats")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("TotalProtein")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocalDate");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("NutriTrack.Domain.Reports.ReportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("FromUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OutputFileName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OutputPdfBlobName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OutputPdfUri")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ParametersJson")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ToUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAtUtc");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("Status");

                    b.ToTable("ReportRuns", (string)null);
                });

            modelBuilder.Entity("NutriTrack.Domain.Social.Snapshots.DailyOverviewSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BurnedCalories")
                        .HasColumnType("int");

                    b.Property<int>("ConsumedCalories")
                        .HasColumnType("int");

                    b.Property<decimal>("ConsumedCarbohydrateGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumedFatGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumedProteinGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExerciseCount")
                        .HasColumnType("int");

                    b.Property<int>("MealCount")
                        .HasColumnType("int");

                    b.Property<int>("NetCalories")
                        .HasColumnType("int");

                    b.Property<int>("RemainingCalories")
                        .HasColumnType("int");

                    b.Property<int>("TargetCalories")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetCarbohydrateGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TargetFatGrams")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TargetProteinGrams")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DailyOverviewSnapshots", (string)null);
                });

            modelBuilder.Entity("NutriTrack.Domain.Social.Snapshots.GoalProgressSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CurrentWeightKg")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime>("GoalStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GoalTargetDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoalType")
                        .HasColumnType("int");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StartWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TargetWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserGoalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserGoalId");

                    b.ToTable("GoalProgressSnapshots", (string)null);
                });

            modelBuilder.Entity("NutriTrack.Domain.Social.SocialPost", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DailyOverviewSnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GoalProgressSnapshotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserAchievementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DailyOverviewSnapshotId");

                    b.HasIndex("GoalProgressSnapshotId");

                    b.HasIndex("UserAchievementId");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("SocialPosts", t =>
                        {
                            t.HasCheckConstraint("CK_SocialPosts_Type_Achievement", "[Type] <> 2 OR ([UserAchievementId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_SocialPosts_Type_DailyOverview", "[Type] <> 3 OR ([DailyOverviewSnapshotId] IS NOT NULL AND [UserAchievementId] IS NULL AND [GoalProgressSnapshotId] IS NULL)");

                            t.HasCheckConstraint("CK_SocialPosts_Type_GoalProgress", "[Type] <> 4 OR ([GoalProgressSnapshotId] IS NOT NULL AND [UserAchievementId] IS NULL AND [DailyOverviewSnapshotId] IS NULL)");

                            t.HasCheckConstraint("CK_SocialPosts_Type_Text", "[Type] <> 1 OR ([Text] IS NOT NULL AND [UserAchievementId] IS NULL)");
                        });
                });

            modelBuilder.Entity("NutriTrack.Domain.UserExercises.UserExerciseLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DurationMinutes")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("OccurredAtLocal")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalCalories")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("LocalDate");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("UserExerciseLogs");
                });

            modelBuilder.Entity("NutriTrack.Domain.UserGoals.UserGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("StartWeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TargetWeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("UserGoals");
                });

            modelBuilder.Entity("NutriTrack.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ActivityLevel")
                        .HasColumnType("tinyint");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateOnly?>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHealthProfileCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("NutritionGoal")
                        .HasColumnType("tinyint");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TotpSecretProtected")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NutriTrack.Domain.WeightHistory.WeightHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("WeightHistoryEntries");
                });

            modelBuilder.Entity("NutriTrack.Infrastructure.Persistence.TwoFactor.PendingLoginChallengeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<bool>("Consumed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("UserId", "Consumed", "ExpiresAtUtc");

                    b.ToTable("PendingLoginChallenges", (string)null);
                });

            modelBuilder.Entity("NutriTrack.Infrastructure.Persistence.TwoFactor.PendingTotpSetupEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecretProtected")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("UserId");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("PendingTotpSetups");
                });

            modelBuilder.Entity("NutriTrack.Domain.Achievements.UserAchievement", b =>
                {
                    b.HasOne("NutriTrack.Domain.Achievements.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriTrack.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriTrack.Domain.ActivityLevelHistory.ActivityLevelHistoryEntry", b =>
                {
                    b.HasOne("NutriTrack.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriTrack.Domain.Authorization.RolePermission", b =>
                {
                    b.HasOne("NutriTrack.Domain.Authorization.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriTrack.Domain.Authorization.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NutriTrack.Domain.Groceries.Grocery", b =>
                {
                    b.OwnsOne("NutriTrack.Domain.Groceries.MacroNutrients", "MacrosPer100", b1 =>
                        {
                            b1.Property<Guid>("GroceryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("CarbsGramsPer100")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("CarbsGramsPer100");

                            b1.Property<decimal>("FatGramsPer100")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("FatGramsPer100");

                            b1.Property<decimal>("ProteinGramsPer100")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("ProteinGramsPer100");

                            b1.HasKey("GroceryId");

                            b1.ToTable("Groceries");

                            b1.WithOwner()
                                .HasForeignKey("GroceryId");
                        });

                    b.Navigation("MacrosPer100")
                        .IsRequired();
                });

            modelBuilder.Entity("NutriTrack.Domain.Meals.Meal", b =>
                {
                    b.HasOne("NutriTrack.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("NutriTrack.Domain.Meals.MealItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("GroceryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("MealId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(9, 2)
                                .HasColumnType("decimal(9,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("GroceryId");

                            b1.HasIndex("MealId");

                            b1.HasIndex("Quantity");

                            b1.ToTable("MealItems", (string)null);

                            b1.HasOne("NutriTrack.Domain.Groceries.Grocery", "Grocery")
                                .WithMany()
                                .HasForeignKey("GroceryId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("MealId");

                            b1.OwnsOne("NutriTrack.Domain.Meals.GrocerySnapshot", "Snapshot", b2 =>
                                {
                                    b2.Property<Guid>("MealItemId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<short>("CaloriesPer100")
                                        .HasColumnType("smallint")
                                        .HasColumnName("CaloriesPer100");

                                    b2.Property<decimal?>("GramsPerPiece")
                                        .HasPrecision(7, 2)
                                        .HasColumnType("decimal(7,2)")
                                        .HasColumnName("GramsPerPiece");

                                    b2.Property<string>("GroceryName")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("GroceryName");

                                    b2.Property<byte>("UnitOfMeasure")
                                        .HasColumnType("tinyint")
                                        .HasColumnName("UnitOfMeasure");

                                    b2.HasKey("MealItemId");

                                    b2.ToTable("MealItems");

                                    b2.WithOwner()
                                        .HasForeignKey("MealItemId");

                                    b2.OwnsOne("NutriTrack.Domain.Groceries.MacroNutrients", "MacrosPer100", b3 =>
                                        {
                                            b3.Property<Guid>("GrocerySnapshotMealItemId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<decimal>("CarbsGramsPer100")
                                                .HasPrecision(5, 2)
                                                .HasColumnType("decimal(5,2)")
                                                .HasColumnName("CarbsGramsPer100");

                                            b3.Property<decimal>("FatGramsPer100")
                                                .HasPrecision(5, 2)
                                                .HasColumnType("decimal(5,2)")
                                                .HasColumnName("FatGramsPer100");

                                            b3.Property<decimal>("ProteinGramsPer100")
                                                .HasPrecision(5, 2)
                                                .HasColumnType("decimal(5,2)")
                                                .HasColumnName("ProteinGramsPer100");

                                            b3.HasKey("GrocerySnapshotMealItemId");

                                            b3.ToTable("MealItems");

                                            b3.WithOwner()
                                                .HasForeignKey("GrocerySnapshotMealItemId");
                                        });

                                    b2.Navigation("MacrosPer100")
                                        .IsRequired();
                                });

                            b1.Navigation("Grocery");

                            b1.Navigation("Snapshot")
                                .IsRequired();
                        });

                    b.Navigation("Items");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriTrack.Domain.Social.Snapshots.GoalProgressSnapshot", b =>
                {
                    b.HasOne("NutriTrack.Domain.UserGoals.UserGoal", "UserGoal")
                        .WithMany()
                        .HasForeignKey("UserGoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("NutriTrack.Domain.Social.Snapshots.GoalProgressSnapshotPoint", "Points", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("Date")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("GoalProgressSnapshotId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("WeightKg")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("GoalProgressSnapshotId", "Date");

                            b1.ToTable("GoalProgressSnapshotPoints", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GoalProgressSnapshotId");
                        });

                    b.Navigation("Points");

                    b.Navigation("UserGoal");
                });

            modelBuilder.Entity("NutriTrack.Domain.Social.SocialPost", b =>
                {
                    b.HasOne("NutriTrack.Domain.Social.Snapshots.DailyOverviewSnapshot", "DailyOverviewSnapshot")
                        .WithMany()
                        .HasForeignKey("DailyOverviewSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NutriTrack.Domain.Social.Snapshots.GoalProgressSnapshot", "GoalProgressSnapshot")
                        .WithMany()
                        .HasForeignKey("GoalProgressSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NutriTrack.Domain.Achievements.UserAchievement", "UserAchievement")
                        .WithMany()
                        .HasForeignKey("UserAchievementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DailyOverviewSnapshot");

                    b.Navigation("GoalProgressSnapshot");

                    b.Navigation("UserAchievement");
                });

            modelBuilder.Entity("NutriTrack.Domain.UserExercises.UserExerciseLog", b =>
                {
                    b.HasOne("NutriTrack.Domain.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NutriTrack.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("NutriTrack.Domain.UserExercises.ExerciseSnapshot", "Snapshot", b1 =>
                        {
                            b1.Property<Guid>("UserExerciseLogId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("CaloriesPerMinute")
                                .HasPrecision(7, 2)
                                .HasColumnType("decimal(7,2)")
                                .HasColumnName("CaloriesPerMinute");

                            b1.Property<byte>("Category")
                                .HasColumnType("tinyint")
                                .HasColumnName("ExerciseCategory");

                            b1.Property<string>("ExerciseName")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("ExerciseName");

                            b1.HasKey("UserExerciseLogId");

                            b1.ToTable("UserExerciseLogs");

                            b1.WithOwner()
                                .HasForeignKey("UserExerciseLogId");
                        });

                    b.Navigation("Exercise");

                    b.Navigation("Snapshot")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriTrack.Domain.UserGoals.UserGoal", b =>
                {
                    b.HasOne("NutriTrack.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriTrack.Domain.Users.User", b =>
                {
                    b.HasOne("NutriTrack.Domain.Countries.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NutriTrack.Domain.Authorization.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NutriTrack.Domain.WeightHistory.WeightHistoryEntry", b =>
                {
                    b.HasOne("NutriTrack.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriTrack.Infrastructure.Persistence.TwoFactor.PendingLoginChallengeEntity", b =>
                {
                    b.HasOne("NutriTrack.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriTrack.Infrastructure.Persistence.TwoFactor.PendingTotpSetupEntity", b =>
                {
                    b.HasOne("NutriTrack.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
